### ISSUE TITLE
主页面Support 功能区的进入及显示

### ISSUE THREAD

**Issue by Fei-Coding** [A-Comosus/comosus-client#18]
主页面Support 功能区的进入及显示

AS an A.C User
I WANT TO be provided with certain guidance or get answer for some questions when using the website
SO THAT I can get additional support and make the user experience more smoothly

当鼠标滑到左下角问号方框的时候，support 功能侧拉框自动浮出
功能项为：
Help Topics （先不做）
Get Started
Ask a question
Submit your feedback

<img width="375" alt="Screen Shot 2022-05-10 at 8 03 55 pm" src="https://user-images.githubusercontent.com/67401672/167604106-b81792e9-13dc-4bcb-b989-c12d9c6d58ca.png">

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
