### ISSUE TITLE
Support 功能区的 Get started

### ISSUE THREAD

**Issue by Fei-Coding** [A-Comosus/comosus-client#19]
点击Get Started的时候， 页面自动跳转到new tab, 如图：
Header 如下图， 可随时回到 linktree主页
Header 下面还有搜索框--可供快速搜索问题及内容
<img width="725" alt="Screen Shot 2022-05-10 at 8 22 44 pm" src="https://user-images.githubusercontent.com/67401672/167607598-b681515d-44ec-409d-9448-c2100828e4bd.png">

内容主要分为两部分：

Getting Started
此信息区的主要内容为 **图一**所示
信息区内 每个功能说明 都可点击浏览，内部页面有详尽的说明，图片或者视频
详情页面 可随时回到Linktree 主页，并有搜索功能
说明结尾 有 供用户 选择的 用后感觉评价 （ 以表情的形式呈现）
Account basics
此信息区的主要内容为 **图二**所示
布局及内容设置如第一部分Getting started, 具体图样 如 **图三**。

图一：
<img width="692" alt="Screen Shot 2022-05-10 at 8 23 31 pm" src="https://user-images.githubusercontent.com/67401672/167607699-84d489ab-0a91-46be-98f2-941f558df344.png">

图二：
<img width="663" alt="Screen Shot 2022-05-10 at 8 23 46 pm" src="https://user-images.githubusercontent.com/67401672/167607738-688f4686-ba82-4d3e-a24a-c1ca31adf515.png">

图三：
<img width="725" alt="Screen Shot 2022-05-10 at 8 24 12 pm" src="https://user-images.githubusercontent.com/67401672/167607815-0e7a9eb9-ba13-4c66-b4c3-ec649b1b50a5.png">

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
