### ISSUE TITLE
Support 功能区的 submit your feedback

### ISSUE THREAD

**Issue by Fei-Coding** [A-Comosus/comosus-client#20]
AS an A.C User
I WANT TO have access to give my feedback online
SO THAT I can let A.C know my user experience and solve the problems i came across

_NOTE: 此部分建议是 我们只做一个feedback类别即可_

当鼠标点击Submit your feedback 的时候
屏幕右下方 跳出自助提问对话框，机器人作答
<img width="340" alt="Screen Shot 2022-05-10 at 8 51 39 pm" src="https://user-images.githubusercontent.com/67401672/167612515-4fc91d25-7ce0-40de-8ea8-d4b09ec7fbdc.png">

对话框文字部分为：
上部是； 
<img width="171" alt="Screen Shot 2022-05-10 at 8 52 06 pm" src="https://user-images.githubusercontent.com/67401672/167612591-ecf2d6dd-e346-4212-9834-6e081b456a89.png">

下部是几个常见feedback选项
<img width="194" alt="Screen Shot 2022-05-10 at 8 35 56 pm" src="https://user-images.githubusercontent.com/67401672/167609847-8bed0fbf-fcc3-4086-a20e-c8499fe10d62.png">

example:
如果点击General feedback, 系统回答跳出，并有可供选择问题的对话框，如下图：
<img width="215" alt="Screen Shot 2022-05-10 at 8 37 30 pm" src="https://user-images.githubusercontent.com/67401672/167610205-d5549d86-a1b5-4cbe-9260-5e3ace2a8452.png">

点击问题选择对话框，问题的类别随机跳出供选择， 如下图：

<img width="223" alt="Screen Shot 2022-05-10 at 8 39 01 pm" src="https://user-images.githubusercontent.com/67401672/167610364-f85b98ca-0598-412c-a2ca-a29364d171a2.png">

当选择了问题类别后， 会接着在下方跳出可供输入具体问题的对话框。
用户可输入，如果输入为空或者有误，会有错误提示显示 如图

<img width="241" alt="Screen Shot 2022-05-10 at 8 40 25 pm" src="https://user-images.githubusercontent.com/67401672/167610640-996ec096-88f8-4e34-9998-d25e1fceede7.png">

当用户一步步输入问题后，系统会终止于最后一个对话框-- 会反馈给公司。

<img width="234" alt="Screen Shot 2022-05-10 at 8 42 05 pm" src="https://user-images.githubusercontent.com/67401672/167610930-6f0ed78c-f919-494e-92c6-e5b9a8cd9916.png">

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
