### ISSUE TITLE
Support 功能区 ASK A QUESTION

### ISSUE THREAD

**Issue by Fei-Coding** [A-Comosus/comosus-client#21]
AS an A.C User
I WANT TO ask some questions online when using AC
SO THAT I can make my user experience more smoothly in the future

NOTE: 建议此处 只 做一个问题类别即可

点击ASK A QUESTION 后，机器人自助问答框显示在页面右下方
<img width="312" alt="Screen Shot 2022-05-10 at 8 55 05 pm" src="https://user-images.githubusercontent.com/67401672/167613112-08b4aa97-f7ba-4e52-bc37-9e8b08d68836.png">

上部分为greetings, 下部为几个问题类别
example:
当点击A BRAND NEW FEATURE OR IDEA
对话框跳转为 下图
greetings 和 问题细分选择框

<img width="264" alt="Screen Shot 2022-05-10 at 8 57 54 pm" src="https://user-images.githubusercontent.com/67401672/167613597-88b072e8-dd8a-4e50-baa1-71dbdf2db8d1.png">

当选择links and button后，会跳出下一层问题对话框，此处需要手动输入
<img width="236" alt="Screen Shot 2022-05-10 at 8 59 10 pm" src="https://user-images.githubusercontent.com/67401672/167613803-b850aba3-d183-4f8c-a1c8-faa388639f1b.png">

对话框进一步引导问题，当用户输入具体问题后，对话框结束于感谢结束于
<img width="234" alt="Screen Shot 2022-05-10 at 9 01 47 pm" src="https://user-images.githubusercontent.com/67401672/167614286-3ff8744f-14d2-40cb-b83f-c1992068bd10.png">

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
