### ISSUE TITLE
"Add new links" 功能页面layout

### ISSUE THREAD

**Issue by Fei-Coding** [A-Comosus/comosus-client#25]
AS an A.C user
I WANT TO type in or paste links to Linktree webpage
SO THAT I can add new links to my personal file created on Linktree

Design 及 AC

AC1:

添加链接前，页面显示“You don't have any links to display. Click the button above to add one"
![Screen Shot 2022-05-12 at 2 09 47 pm](https://user-images.githubusercontent.com/67401672/167990343-254a062c-14a8-41d2-b15e-172094b1ee87.png)

AC2:
点击Add New LInk 后， 下方出现编辑链接的编辑框，如下图:
左侧
分割栏

中间部分：
链接标题栏
超链接网址
工具栏

右侧
隐藏键
删除键
![Screen Shot 2022-05-12 at 2 18 35 pm](https://user-images.githubusercontent.com/67401672/167991255-c0176030-6bb2-4885-8df6-c04235309df5.png)

删除键：
点击删除键后，跳出 确认删除请求的对话框
可以选择cancel 或者 Delete to proceed
如果点击cancel, 则对话框消失，回到编辑link 对话框
如果点击Delete, 则此Link 编辑框消失，回到Add New Link 主页面

![Screen Shot 2022-05-12 at 3 04 23 pm](https://user-images.githubusercontent.com/67401672/167995791-2db58b28-c1cf-43a9-a4aa-c20a868ad54a.png)

工具栏详情：
1， Redirect
点击redirect 键， 此工具变为蓝色，同时跳出Redirect 工具框， Redirect 键旁有问号（为不知道此工具用处的用户提供说明）
点击问号，页面会跳到一个 HOW TO SET UP A REDIRECT LINK 的说明详情页， 如图。
Note: Redirect 工具 只能Upgrade 后 才能使用。
如果想关闭此工具页， 点击右上角的X 即可。

2.Thumbnail 工具
点击Thumbnail, 工具呈现蓝色，同时跳出Add Thumbnail 工具框， 此工具无需升级即可使用

![Screen Shot 2022-05-12 at 2 25 59 pm](https://user-images.githubusercontent.com/67401672/167991969-ff8d13ac-c773-4187-9c5f-af7403cbfc8c.png)

点击”Set Thumbnail“, 跳出Add Thumbnail的 对话框

![Screen Shot 2022-05-12 at 2 32 48 pm](https://user-images.githubusercontent.com/67401672/167992590-b0a5d5e8-0e76-4d19-8754-3e89ac26dc65.png)

添加的方式有两种： Upload your own thumbnail / Choose from Tabler Icons

![Screen Shot 2022-05-12 at 2 34 52 pm](https://user-images.githubusercontent.com/67401672/167992766-b95582ee-6cf4-4417-a6e6-bde05171a838.png)

如果选择Upload your own thumbnail --- 点击选项右侧的箭头后， 页面跳出上传文件对话框
对话框左侧有文件source 的选项
![Screen Shot 2022-05-12 at 2 35 11 pm](https://user-images.githubusercontent.com/67401672/167992791-99541f0b-7856-4f1d-8267-eab55eff04ee.png)

如果选择choose from Tabler Icons
页面跳转至Tabler Icons source pool
![Screen Shot 2022-05-12 at 2 36 37 pm](https://user-images.githubusercontent.com/67401672/167992927-2592bd11-b9fa-4a51-bf63-8b97f04ab6e1.png)

3. Prioritize 工具
点击后，工具图标呈现蓝色，同时跳出Prioritize 工具对话框，此工具需要升级后才使用

![Screen Shot 2022-05-12 at 2 38 05 pm](https://user-images.githubusercontent.com/67401672/167993071-c058c570-7af0-4ba5-a04b-3ce949fd09ca.png)

4. Schedule 工具
此工具需升级后才能使用
![Screen Shot 2022-05-12 at 2 40 02 pm](https://user-images.githubusercontent.com/67401672/167993274-6ced7553-671a-4bdc-9a39-3c5e9e96de0f.png)

5. Lock 工具
点击后，此工具图标变为蓝色，同时跳出工具对话框，如下图
对话框内包含信息为：
Lock this link 指示语
Visitors can only access this link by fulfilling certain criteria ( 对此功能的简要说明）
Link locked with 的方式选项
Code ( 此选项需要升级才能使用）
Date of Birth
Sensitive Content
NFT Contract Address

![Screen Shot 2022-05-12 at 2 40 36 pm](https://user-images.githubusercontent.com/67401672/167993333-072552cf-6905-4c22-8199-26c7e773749e.png)

点击 Date of Birth 选项
跳出对话框如下图：

![Screen Shot 2022-05-12 at 2 47 52 pm](https://user-images.githubusercontent.com/67401672/167994053-18c79f2a-b031-4218-8e21-c15c1d992655.png)

点击Sensitive Content, 跳出对话框如下：
![Screen Shot 2022-05-12 at 3 01 11 pm](https://user-images.githubusercontent.com/67401672/167995491-e2540def-6af7-4f30-8fa9-830006662acb.png)

点击NFT Contract Address, 跳出对话框如下：
![Screen Shot 2022-05-12 at 3 01 53 pm](https://user-images.githubusercontent.com/67401672/167995562-61ccc9eb-37ed-423a-a170-05a34adac588.png)

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
