### ISSUE TITLE
as a user, I want to have a guide on get set up, so that I can have a guide and know the progress of the setting

### ISSUE THREAD

**Issue by song-jinchen** [A-Comosus/comosus-client#27]
![image](https://user-images.githubusercontent.com/62097270/168041446-60907986-363c-4671-a13d-1d6f7f7e25d6.png)
the get set up button should be on the right down side of the page

**Comment by song-jinchen** [comment]
and the system shall have the function to let the customers know after they creat their firstlink, add the linktree everywhere, and update the profile image and theme

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
