### ISSUE TITLE
as a user,  I want to have a upgrade function on the homepagr negivation bar, so that i can upgrade to a member when I want to pay for more function

### ISSUE THREAD

**Issue by song-jinchen** [A-Comosus/comosus-client#29]
![image](https://user-images.githubusercontent.com/62097270/168044626-3dd08990-c453-4634-a6a8-e5d5dd17bbcf.png)
![image](https://user-images.githubusercontent.com/62097270/168044720-abe4c601-a1ed-42dd-9a68-506b57d5d7ef.png)
the system shall avaliabe to describe what is the benefit of each kind of the plan and which one is recommand to the customer

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
