### ISSUE TITLE
as a user,  I want to have a support function when in the right downside of the home page, so that I can ask for help when I have question about he website,

### ISSUE THREAD

**Issue by song-jinchen** [A-Comosus/comosus-client#31]
![image](https://user-images.githubusercontent.com/62097270/168415732-e5fbc1c0-a613-427c-aa24-f9351adbf76c.png)
the support should have contact function which can directly send the email to the sever side, which the supporter can recieve the message and get in touch as soon as possible.
the support shall have the function which the customer can talk with th supporter in the realtime, and get help directly.
the system shall have list the comon question that most of the customer will meet and they shall search the question directly to solve the  problem by themselves.

**Comment by song-jinchen** [comment]
![image](https://user-images.githubusercontent.com/62097270/168416015-7b13049c-dd83-49d3-919c-87512577d4d3.png)
also this can appear on the left downside of the website and hae the same function with the right side one.

**Comment by NorrisWu0** [comment]
Closing this issue since we have migrated to Jira
